#' @title Clean ThetaProbe data for outliers in five minute data and save a CSV file of daily data
#'
#'@description This function checks for and removes outliers in the
#'University of Southern Queensland National Centre for Engineering in
#'Agriculture's (NCEA) Theta Probe data of soil moisture for Dr. Jo White,
#'saving the results as a CSV file with daily values
#'
#' @param csv_in A CSV file generated by \link{get_soil_moisture}, which should
#' be cleaned of outliers and aggregated to daily values
#'
#' @details This function will check the CSV file for outliers in five minute
#' data, filter them and generate a new file with daily moisture values that will
#' be written to disk in the user's specified location.
#'
#' @examples
#' \dontrun{
#' cleaned <- clean_theta_data(csv = "~/Documents/Data/Theta Probe/2016-08-24_Soil_Moisture.csv",
#' path = "~/Documents/Data/Theta Probe/")
#'
#' write.csv(cleaned, "~/Documents/cleaned_data.csv")
#' }
#' @export

clean_theta_data <- function(csv_in = NULL) {

  Date <- Probe <- Moisture <- NULL

  # import data ----------------------------------------------------------------
  observations <- as.data.frame(
    readr::read_csv(csv_in, col_names = c("Date", "Time", "Moisture", "Probe")))

  # reformate date column ------------------------------------------------------
  observations[, 1] <- gsub(pattern = "/", replacement = "", observations[, 1])
  observations[, 1] <- lubridate::dmy(observations[, 1])

  # filter ouliers -------------------------------------------------------------
  observations$Filtered_Moisture <- pracma::hampel(observations[, 3], 4, t0 = 3)$y

  # aggregate to daily values --------------------------------------------------
  aggregated <- doBy::summaryBy(Moisture ~
                      as.Date(observations$Date, origin = "1960-01-01") +
                      as.character(observations$Probe),
                      data = observations,
                      FUN = mean)
  aggregated[, 3] <- round(aggregated[, 3], 2)

  # arrange by Probe then date and return tibble object ------------------------
  names(aggregated) <- c("Date", "Probe", "Moisture")

  aggregated <- dplyr::arrange(aggregated, Probe, Date)

return(aggregated)
}

