#' @title Clean ThetaProbe data for outliers in hourly data
#'
#'@description This function checks for and removes outliers in the
#'University of Southern Queensland National Centre for Engineering in
#'Agriculture's (NCEA) Theta Probe data of soil moisture for Dr. Jo White.
#'
#' @param path #' @param path Filepath to directory where a comma separated
#' file (CSV) exists, which must be generated by the get_soil_moisture()
#' function. This is the directory where the new CSV of daily values will be
#' placed as well.
#' @param csv A CSV file generated by get_soil_moisture()
#'
#' @details This function will check the CSV file for outliers in hourly data
#' and remove them and generate a new file with daily moisture values
#'
#' @examples
#' # NULL
#' @export

remove_outliers <- function(csv = NULL, path = NULL) {
soil <- readr::read_csv(csv)


soil$Filtered_Moisture <- pracma::hampel(soil[, 3], 4, t0 = 3)$y

doBy::summaryBy

utils::write.csv(soil, path = paste0(path, "/"), row.names = FALSE)

}


