#' @title Clean ThetaProbe data for outliers in hourly data
#'
#'@description This function checks for and removes outliers in the
#'University of Southern Queensland National Centre for Engineering in
#'Agriculture's (NCEA) Theta Probe data of soil moisture for Dr. Jo White.
#'
#' @param path Filepath to directory where a comma separated
#' file (CSV) exists, which must be generated by the get_soil_moisture()
#' function. This is the directory where the new CSV of daily values will be
#' placed as well.
#' @param csv A CSV file generated by get_soil_moisture()
#'
#' @details This function will check the CSV file for outliers in five minute
#' data, filter them and generate a new file with daily moisture values that will
#' be written to disk in the user's specified location.
#'
#' @examples
#' \dontrun{
#' remove_outliers(csv = "~/Documents/Data/Theta Probe/2016-08-24_Soil_Moisture.csv",
#' path = "~/Documents/Data/Theta Probe/")
#' }
#' @export

remove_outliers <- function(csv = NULL, path = NULL) {

  path <- .get_data_path(path)

  csv <- utils::read.csv(csv, head = FALSE)
  names(csv) = c("Date", "Time", "Moisture", "Probe")
  csv$Filtered_Moisture <- pracma::hampel(csv[, 3], 4, t0 = 3)$y

  aggregated <- doBy::summaryBy(csv$Filtered_Moisture ~
                                  as.character(csv$Date) +
                                  as.character(csv$Probe),
                  data = csv, FUN = mean)

  utils::write.csv(aggregated, paste(path, "Daily_Soil_Moisture.csv"))
}

#' @noRd
# shamelessly borrowed from RJ Hijmans Raster package
.get_data_path <- function(path) {
  path <- trimws(path)
  if (is.null(path)) {
    path <- getwd()
  } else {
    if (substr(path, nchar(path) - 1, nchar(path)) == "//") {
      p <- substr(path, 1, nchar(path) - 2)
    } else if (substr(path, nchar(path), nchar(path)) == "/" |
               substr(path, nchar(path), nchar(path)) == "\\") {
      p <- substr(path, 1, nchar(path) - 1)
    } else {
      p <- path
    }
    if (!file.exists(p) & !file.exists(path)) {
      stop("File path does not exist: ", path)
    }
  }
  if (substr(path, nchar(path), nchar(path)) != "/" &
      substr(path, nchar(path), nchar(path)) != "\\") {
    path <- paste0(path, "/")
  }
  return(path)
}

